language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  - GOOGLE_CLOUD=">=0.10.2 <0.14"
  - GOOGLE_CLOUD=">=0.21 <0.36"
  - GOOGLE_CLOUD=">=0.36"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - bash -c 'if [[ "${TRAVIS_PHP_VERSION}" == "hhvm" ]]; then rm phpunit.xml; mv phpunit.hhvm.xml phpunit.xml; fi;'

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry composer require --no-interaction --no-suggest "google/cloud:${GOOGLE_CLOUD}"

script:
  - bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash -c 'if [[ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
